/*
 * generated by Xtext
 */
package net.sf.orcc.cal.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.sf.orcc.cal.services.CalGrammarAccess;

public class CalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CalGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.sf.orcc.cal.parser.antlr.internal.InternalCalParser createParser(XtextTokenStream stream) {
		return new net.sf.orcc.cal.parser.antlr.internal.InternalCalParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AstEntity";
	}
	
	public CalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
